@startuml aladin_task_process
'https://plantuml.com/activity-diagram-beta

|Backend|
    start
    group "Define the Task" {
        :Define the API;
        :Define the Worker;
        group "Define the UI" {
            :Define UI interfaces;
            :Define interface order;
            :Define hints;
        }
        :Program the Task Generator;
    }
    :Backend creates API to fetch
    task definition and generated task|
|Frontend|
    :Fetch task definition;
    :Initialize the UI;
    :Choose task to solve;
    group "Execute the Task" {
        note right
            Record all actions for the replay
        end note
        :Set parameters for task generation;
        :Fetch generated task from backend;
        while (Subtasks available?)
            if (Multiple solving paths available?)
                :Choose path;
            endif
                :Solve (sub-)task;
        endwhile
        :Task finished|
        :Save the replay;
    }
|Backend|
    :Locally storing the replay;
    end
@enduml
