@startuml communication_interfaces

'skinparam monochrome true

title "Gamification Schnittstelle"

"Benutzer" as U

rectangle "Lernplattform ALADIN" {
  file "Aufgabendefinition.json" as TD
  node "Aufgabe" as T
  collections "Aufzeichnung/Replay.json" as RP
}

file "Gamificationdefinition" as GD #gold

rectangle "SkillTree Plattform" {
  [Projekt]
  [Themengebiet]
  [Gruppe]
  [Fähigkeit]
}
TD --> T : definiert
T "n" <-l- "n" U : bearbeitet
T ..> RP : führt zu
RP -right(0- GD : verbindet
GD -right0)- [Fähigkeit]: mit
[Projekt] "1" *-- "n" [Themengebiet]
[Themengebiet] "1" *-- "n" [Gruppe]
[Gruppe] "n" *-- "n" [Fähigkeit]
[Themengebiet] "n" *-- "n" [Fähigkeit]

@enduml