@startuml communication_interfaces

'skinparam monochrome true

title "Gamification Schnittstelle"

"Benutzer" as U

rectangle "Lernplattform ALADIN" {
  file "Aufgabendefinition.json" as TD
  node "Aufgabe" as T
  collections "Aufzeichnung/Replay.json" as RP
}

file "Gamificationdefinition" as GD #gold

rectangle "SkillTree Plattform" {
  [Projekt]
  [Themengebiet]
  [Fähigkeitengruppe\n(Skill-Gruppe)] as SG
  [Fähigkeit\n(Skill)] as S
}
TD --> T : definiert
T "n" <-l- "n" U : bearbeitet
T ..> RP : führt zu
RP -right(0- GD : verbindet
GD -right0)- S: mit
[Projekt] "1" *-- "n" [Themengebiet]
[Themengebiet] "1" *-- "n" SG
SG "n" *-- "n" S
[Themengebiet] "n" *-- "n" S

@enduml