@startuml

skinparam monochrome true

title "Communication and interfaces"

"User" as U

rectangle "ALADIN - Learning Platform" {
  file "Task definition" as TD #white
  node "Task" as T
  collections "Replay" as RP #white
}

file "Gamification definition" as GD #white

rectangle "Skill Tree Platform" {
  [Projects]
  [Subjects]
  [Groups]
  [Skills]
}
T ..> RP : leads to
TD --> T : defines
RP -right(0- GD : maps
GD -right0)- [Skills]: to
T "n" <-l- "n" U : executes
[Projects] "1" *-- "n" [Subjects]
[Subjects] "1" *-- "n" [Groups]
[Groups] "n" *-- "n" [Skills]
[Subjects] "n" *-- "n" [Skills]

@enduml